In [1]:
#Create a data file by using Python random module with different random generator parameters. The data file must have 20000 × 10000 (rows × columns). This data file is to be used as a database for realization of math and matrix operations in cloud computing lab assignments.

import numpy as np

rows = 20000
cols = 10000

# generate random data
data = np.random.uniform(low=0, high=100, size=(rows, cols)).astype(np.float32)

# save to file
np.save("large_random_data.npy", data)

print("Data file created and saved successfully!")


Data file created and saved successfully!


In [2]:
#Write a program in Python to assign subsequent rows to matrix first row elements.

import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

first_row = matrix[0]

result = matrix.copy()
for i in range(1, matrix.shape[0]):
    result[i] = first_row

print("Resultant Matrix:")
print(result)


Resultant Matrix:
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [3]:
#Write a program in Python to group similar elements into matrix

import numpy as np

data = [1, 2, 1, 3, 2, 3, 1, 2]
unique_elements = sorted(set(data))

grouped_matrix = []

for element in unique_elements:
    grouped_matrix.append([x for x in data if x == element])

print("Grouped Matrix:")
print(grouped_matrix)


Grouped Matrix:
[[1, 1, 1], [2, 2, 2], [3, 3]]


In [4]:
#Write a program in Python to add and subtract matrices

import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

addition = A + B
subtraction = A - B

print("Addition:")
print(addition)

print("Subtraction:")
print(subtraction)


Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]


In [5]:
#Write a program in Python to create an n × n square matrix, where all the sub-matrix has the sum of opposite corner elements as even.

import numpy as np

n = 4
matrix = np.zeros((n, n), dtype=int)

# fill with even numbers to satisfy condition
for i in range(n):
    for j in range(n):
        matrix[i][j] = 2 * (i + j)

print("Square Matrix:")
print(matrix)


Square Matrix:
[[ 0  2  4  6]
 [ 2  4  6  8]
 [ 4  6  8 10]
 [ 6  8 10 12]]


In [6]:
#Write a program in Python to perform row-wise element addition in tuple matrix.

tuple_matrix = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)

row_wise_sum = [sum(row) for row in tuple_matrix]

print("Row-wise Addition:")
print(row_wise_sum)


Row-wise Addition:
[6, 15, 24]
